### ISSUE TITLE
Documentation website not found

### ISSUE THREAD

**Issue by A-Ivan** [pollen-robotics/reachy-unity-package#1]
Hi Pollen Robotics.

I just wanted to let you know that the documentation link on your Readme file leads to a 404 "There isn't a GitHub Pages site here. ".

"
For more information on how to get started: https://pollen-robotics.github.io/reachy-docs/
"

Is it supposed to go to the 2021 documentation page?
https://docs.pollen-robotics.com/

Or the 2019 documentation page?
https://pollen-robotics.github.io/reachy-2019-docs/

**Comment by pierre-rouanet** [comment]
Thanks! I've fixed the link.
