### ISSUE TITLE
VR Support

### ISSUE THREAD

**Issue by A-Ivan** [pollen-robotics/reachy-unity-package#2]
Hi Pollen Robotics,

Is there a specific repository for simulated (Unity-based) VR control of Reachy? Similar to the images shown on the Teleoperation page - https://docs.pollen-robotics.com/vr/use-teleop/commands/

If not, are there any plans for when it will be released?

If not, what would be the best way to create this VR control (using Valve Index or HTC Vive) using this repository?

Thank you.

**Comment by pierre-rouanet** [comment]
Hi,

Our teleop-app is not public yet. We are still trying to figure out the best way to do this.
If you want to work on something similar, you have to look at our SDK API: https://github.com/pollen-robotics/reachy-sdk-api and the C# binding to connect with the robot.

**Comment by A-Ivan** [comment]
Hi Pierre,

Thank you for your reply. Is there any expectation you could provide on when you hope/plan on having this publicly available, for instance, by the end of 2021?

I ask because it seems like you guys have already done everything, so if it will be released by the end of the year I could just wait until then instead of recreating it myself.

**Comment by pierre-rouanet** [comment]
Sorry for the not really precise answer but we are really busy working on some further developments for Reachy tele-operation until the end of the year. So it's really unlikely that we have time to work on releasing something before that.

**Comment by A-Ivan** [comment]
Hi Pierre,

That's alright. Good luck on the development, I hope everything works out well. I'll check back here early next year then to see if there is any update.

**Comment by A-Ivan** [comment]
Hi @pierre-rouanet ,

I wanted to check if there is any update on a public release of the Reachy for VR teleoperation? We have the Reachy at our lab and were hoping to run some VR experiments that we would create in Unity to use Reachy.

Is there any release date on when the 2021 version of the Unity package will be available? For those that already have access to Reachy, would we be able to get an early access to the package?

Thank you.

**Comment by atx-barnes** [comment]
@pierre-rouanet Any update on this thread? Looking forward to trying out the VR teleportation functionality

**Comment by FabienDanieau** [comment]
Hi @atx-barnes we do not have an official release date right now, but this is something we are working on. We'll keep you posted
